name: CI (Build)

on:
  pull_request:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc
        runs-on:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }} --all-features
      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }} --all-features

      - name: Test release build with debug assertions
        run: cargo test --release --all-features
        env:
          CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS: true
          CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS: true

      - name: Test release build without debug assertions
        run: cargo test --release --all-features

      - name: Upload proptest regressions
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: proptest-regressions
          path: tests/*.proptest-regressions

      - name: Check format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --no-deps
